.RECIPEPREFIX +=

/tmp/fdk-aac/.libs/libfdk-aac.a: /bin/autoreconf /bin/libtool \
/bin/x86_64-w64-mingw32-g++ /bin/git
  ./make.sh

/bin/autoreconf:
  sage install automake

/bin/libtool:
  sage install libtool

/bin/x86_64-w64-mingw32-g++:
  sage install mingw64-x86_64-gcc-g++

/bin/git:
  sage install --nodeps git
